name: Hugging Push
description: GitHub action that'll push files of the current github code repository to the hugging face space code repository.
author: backendcloud
branding:
  icon: refresh-cw
  color: green

inputs:
  huggingface_repo:
    type: string
    default: 'same_with_github_repo'
  hf_token:
    required: true
  repo_type:
    type: string
    default: 'space'
  space_sdk:
    type: string
    default: 'gradio'
  private:
    type: boolean
    default: false

runs:
  using: "composite"
  steps:
    - name: Checkout current Repo
      uses: actions/checkout@v2
    - name: Push to Hugging Face
      shell: bash
      run: |
        cd ${{ github.action_path }}
        pip install -r requirements.txt
        cd ~
        python ${{ github.action_path }}/push.py \
          --huggingface_repo ${{ inputs.huggingface_repo }} \
          --github_repo ${{ github.repository }} \
          --token ${{ inputs.hf_token }} \
          --repo_type ${{ inputs.repo_type }} \
          --space_sdk ${{ inputs.space_sdk }} \
          --private ${{ inputs.private }}